### ISSUE TITLE
Web editor

### ISSUE THREAD

**Issue by Unknwon** [gogits/gogs#3460]
Web editor for repository files are now in public beta in `master` branch and demo site (https://try.gogs.io), but not yet fully done.

Todos/issues:

- [x] [Web editor should use proper author name and email](https://github.com/gogits/gogs/issues/3505)
- [x] Improve code quality
- [x] Mirror repository should not allow edit
- [x] [Web editor changes line endings to DOS](https://github.com/gogits/gogs/issues/3516)
- [x] [Cannot create new file in subdirectory](https://github.com/gogits/gogs/issues/3460#issuecomment-243028652)
- [x] [Re-enable upload files](https://trello.com/c/bmF3YnbR/817-web-editor-re-enable-upload-files)

I'll maintain this list based on feedback in comments.

**Besides, to keep this thread clean and focus on implementation, there are some rules of comment in this thread; violate to those rules will result in deletion of your comment without warning:**

1. Do not comment unless you have a bug report with reproduce steps on demo site (https://try.gogs.io)
2. Do not post duplicated or irrelavent problems
3. Use reactions

**Comment by richmahn** [comment]
@Unknwon I don't understand the mirror repositories should not allow edit item. Like Github, even a repo that you can't edit still has an edit icon and has you fork it if you can't edit. Or are you saying if someone mirrors my repo, currently I can edit their repo but shouldn't be able to? How to reproduce what you saw?

**Comment by Unknwon** [comment]
@richmahn You simply can't push changes to a mirror repository in Gogs, this is by Gogs's definition. You can also fork but can't send pull request.

**Comment by joubertredrat** [comment]
This is results from my first test

* If I edit js, json, css, php files, tabulation doesn't work fine, `tab` work fine, but `alt + tab not`.
* If I edit txt files, `tab` add more tabulation normally, but `alt + tab` remove all tabulation one time, and the correct was to remove the tabulation one by one.
* On md files, both `tab` and `alt + tab` works fine.
* I think that is good to `?` tooltip explain that if you change name on input, Gogs will rename file.
* Toggle side by side is amazing, nice option.

I will continue testing to see if I have more impressions.

**Comment by Unknwon** [comment]
@joubertredrat what does `alt + tab` doe?

**Comment by joubertredrat** [comment]
> @joubertredrat what does alt + tab doe?

LOL sorry, I was solving another problem about `alt`, the correct is `shift + tab`, fixed above too.

**Comment by Unknwon** [comment]
@joubertredrat tested on demo site with Chrome and `shift + tab` works as expected..

**Comment by joubertredrat** [comment]
> @joubertredrat tested on demo site with Chrome and shift + tab works as expected.

@Unknwon You edited md files, text files or another language files? I tested here again with Chrome on both Linux and Windows

* https://try.gogs.io/redrat/ajaxtable/src/master/js/ajaxtable.js = `tab` work, `shift + tab` no
* https://try.gogs.io/redrat/ajaxtable/src/master/LICENSE = `tab` work, `shift + tab` no (remove all tabulation one time).
* https://try.gogs.io/redrat/ajaxtable/src/master/README.md = `tab` work, `shift + tab` work

I will view here If I can provide a small video with this issue.

**Comment by Unknwon** [comment]
@joubertredrat yes, all works, but indeed for code file `shift + tab` sometimes delete more than it should. But I don't see any code handles tab in Gogs codebase, so I guess it is upstream bug of CodeMirror maybe.

**Comment by joubertredrat** [comment]
@Unknwon Ok, I will test here to see if I can reproduce this issue directly on CodeMirror

**Comment by fontenele** [comment]
Testing in firefox:

- Creating _txt_ files: **OK**
- Editing _txt_ files: **OK**
- Creating _php_ files: OK but indentation is using 2 spaces, normally we use 4 spaces in PHP
- Previewing _php_ files: indentation is confused on preview, but when editing this is OK
- Editing _php_ files: when i go to preview changes without make any changes, it shows me i changed all the file on the diff preview. 

Continue testing...

**Comment by fontenele** [comment]
- Creating _js_ files: **OK**
- Editing _js_ files: **OK**
- Previewing _js_ files: **OK**

**Comment by fontenele** [comment]
- Creating _json_ files: **OK**
- Editing _json_ files: **OK**
- Previewing _json_ files: **OK**
- **ALL FILES EXTENCIONS** I edit, without have any change i click in preview then show me as i have changed all the file.

**Comment by Unknwon** [comment]
Line endings can be different which cause unnecessary diff.

**Comment by joubertredrat** [comment]
https://github.com/codemirror/CodeMirror/issues/4177

**Comment by yymhsy** [comment]
@Unknwon 一进来看到他们问的都太高深，想问下如何做到开机重启gogs啊，没看到有介绍这方面的

**Comment by joubertredrat** [comment]
@Unknwon for `shift + tab`, is possible to remap keys, on link below have more about this.

https://github.com/codemirror/CodeMirror/blob/master/keymap/sublime.js#L95
You can test this on https://codemirror.net/demo/sublime.html

**Comment by andreynering** [comment]
@joubertredrat I played a little with these configs on #3512

**Comment by Unknwon** [comment]
@andreynering does these configs take effect if no `.editorconfig`?

**Comment by andreynering** [comment]
@Unknwon 

@richmahn have set some defaults (indentation size). My PR override these defaults if a `.editorconfig` is present.

@joubertredrat's issue of using `shift + tab` to unindent is a separated issue, so yeah that is still to be fixed.

**Comment by richmahn** [comment]
Sorry guys, been away from doing any Gogs development, instead been working with AWS Lambda and API Gateway for a whole new system, so had no time, but do need to get back to Gogs in the changes I make for my organization. Anyway, I am not even sure where this Web Editing feature is at, changes people have wanted, and if anything is depending on me or if this is more or less out of my hands. If editing should work different than with Github (haven't tried to wrap my mind around @Unknwon's response about forking and PRs to understand the differences if any), and my code doesn't handle this right, has anyone made changes? Let me know if anything is waiting on me.

**Comment by Unknwon** [comment]
@richmahn Thanks. I made some quick changes to merge the branch so people can start testing. But many detailed works are still going on. (listed in my original comment of this thread)

**Comment by richmahn** [comment]
@Unknwon Ok, so this is still an open issue. I saw that the re-enable upload is there, and now saw that you commented out the link for uploading files. Did you make a comment elsewhere on what was wrong with how I did uploading files? It does use a new table in the database, so not sure if maybe I didn't hook that up right to auto-create the table? It's been a while since I worked on that piece so don't remember much. Let me know the issue there and how we can get uploading turned back on.

**Comment by Unknwon** [comment]
@richmahn no, just because I don't have enough time t quick review uploads. (we can chat on gitter.im to keep this thread clean)

**Comment by atomi** [comment]
unable to create new files in subdirectories
`editor.failed_to_update_file%!(EXTRA *errors.errorString=git mv foo foo/test.md: exit status 128 - fatal: can not move directory into itself, source=foo, destination=foo/test.md )`

I created a test repo https://try.gogs.io/atomi/test/src/master/foo if you try to use 'new file' in a subdirectory you get the above errror.

**Comment by Unknwon** [comment]
@atomi things should be good now!

**Comment by Unknwon** [comment]
The feature set is now complete.

**Comment by joubertredrat** [comment]
@andreynering then you or me open issue about indentation?

**Comment by andreynering** [comment]
@joubertredrat You can open
